config/routes.rb
Rails.application.routes.draw do
  resources :messages

  post '/:integration_name' => 'webhooks#receive', as: :receive_webhooks

  # constraints subdomain: 'hooks' do
  #   post '/:integration_name' => 'webhooks#receive', as: :receive_webhooks
  # end


  root 'messages#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    PHONE_REGEX = /^(\+1)?\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$/

    before_validation :strip_phone

    validates :sender_name, :length => { :minimum => 3 }
    validates :phone, :length => { :minimum => 7 }, format: { with: /(\+?1?\d{3}-?\d{3}-?\d{4})/, message: "bad format in phone number" }
    before_save :clean_phone

    def strip_phone
        self.phone = self.phone.to_s.strip
    end

    def clean_phone
        self.phone = ActionController::Base.helpers.number_to_phone(self.phone.to_s.gsub(/[^0-9+]/, ''))
    end

    def sms_send
        account_sid = 'AC02db1aa53f22a8be4c4a474b0dcaca5c'
        auth_token = 'caefa5304fc5dd1b1087920d79b66fde'
        twilio_number = '+14437753675'
        client = Twilio::REST::Client.new(account_sid, auth_token)

        client.messages.create(
            to: self.phone,
            from: twilio_number,
            body: self.body)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :set_new_message, only: [:new]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    if @message.save
      begin
        @message.sms_send
        redirect_to new_message_path(@message, id: @message.id, notice: 'Message was successfully sent.')
      rescue Exception => e
        @message.destroy
        redirect_to new_message_path(@message, alert: "Message failed: #{e.message}.")
      end
    else
      redirect_to new_message_path(@message, notice: "Message failed.")
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    def set_new_message
      @message = Message.new
      if params.has_key?(:id)
        msg = Message.find(params[:id])
        @message.sender_name = msg.sender_name
        @message.phone = msg.phone
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:sender_name, :phone, :body)
    end
end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
  skip_before_action :verify_authenticity_token

  def receive
    # <?xml version="1.0" encoding="UTF-8"?>
    # <Response>
    #     <Say>Thanks for calling!</Say>
    # </Response>

    begin
      if request.headers['Content-Type'] == 'application/json'
        js = JSON.parse(request.body.read)
      elsif request.headers['Content-Type'] == 'text/xml' # or 'text/html'?
        js = Hash.from_xml(request.body.read).to_json
      else
        # application/x-www-form-urlencoded
        js = params.as_json
      end


      if Rails.env.development?
        logger.debug request.headers['Content-Type']
        logger.debug "Params Sent: #{js.to_s}"
      end

      @message = Message.new(json_to_message_params(js))
      if @message.save()
        head :ok
      else
        logger.info "webhooks#receive rejected sms message from provider:"
        logger.info "Params Sent: #{js.to_s}"
        logger.info "Message parameters: #{json_to_message_params(js).to_s}"

        head :unprocessable_entity
      end

    rescue Exception => e
      puts e.message
      head :unprocessable_entity
    end
  end

  def json_to_message_params(js)
    p = {}
    p[:sender_name] = js['From']
    p[:phone] = js['To']
    p[:body] = js['Body']
    p
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def message_datetime(d)
        d.localtime.strftime('%l:%M:%S %p  %B %e, %Y')
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sms</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    <% if Rails.env.development? %>
      <h6><%= params.to_s %></h6>
    <% end %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :sender_name %>
    <%= form.text_field :sender_name, id: :message_sender_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :phone %>
    <%= form.phone_field :phone, id: :message_phone, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, id: :message_body, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit("Send Message", class: "btn btn-primary") %>
  </div>
<% end %>

app/views/messages/_message_list.html.erb
  <div class="panel panel-default">
    <% messages = Message.where(sender_name: message.sender_name)
      .or(Message.where( sender_name: message.phone))
      .order("created_at DESC") %>
    <% messages.each do |msg| %>
      <div class="panel-body">
        <div class="msg-header">
          <div class="msg_field"><%= msg.sender_name %></div>
          <div class="msg_field"><%= msg.phone %></div>
          <div class="msg_field"><%= message_datetime(msg.created_at) %></div>
        </div>
        <div class="msg_body">
          <%= msg.body %>
        </div>
      </div>
    <% end %>
  </div>
  <br>

app/views/messages/edit.html.erb
<div class="page-header">
	<h1>Send Message</h1>
</div>

<%= render 'form', message: @message %>

<hr>

<%= render 'message_list', message: @message %>


<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Sender name</th>
      <th>Phone</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.sender_name %></td>
        <td><%= message.phone %></td>
        <td><%= message.body %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<div class="page-header">
	<h1>Send Message</h1>
</div>

<%= render 'form', message: @message %>
<hr>
<%= render 'message_list', message: @message %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sender name:</strong>
  <%= @message.sender_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @message.phone %>
</p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>